### ISSUE TITLE
Jellyfin should be included in the list of body base applications

### ISSUE THREAD

**Issue by gauvingingras** [packruler/traefik-themepark#10]
**Describe the bug**
The Jellyfin application should be included in the list of body based application, as it loads its own styles from the body.

**Relevant Config**
Workaround is to add the following to configure the middleware for Jellyfin:
`traefik.http.middlewares.jellyfin-themepark.plugin.traefik-themepark.target=</body>`

**Expected behavior**
The style link to be added in the body.

**Actual behavior**
The style link is added in the head.

**Server (please complete the following information):**
 - OS: Docker on Raspberry Pi 4
 - Traefik Version 2.9.6
 - Plugin Version 1.2.2

**Comment by packruler** [comment]
I have pushed an update for this in [v1.3.0](https://github.com/packruler/traefik-themepark/releases/tag/v1.3.0)

**Comment by ALameLlama** [comment]
@packruler It looks like radarr and prowlarr will also need sub filtering to work correctly

**Comment by packruler** [comment]
I made a ticket for that update: #11 It should be quick to do but may not get to it until this weekend. Please direct any comments to that ticket

**Comment by jpdsc** [comment]
@packruler , looks like this issue is now also visible on Sonarr version: 4.0.1.929
