### ISSUE TITLE
Theme for bazarr doesn't work properly after recent updates.

### ISSUE THREAD

**Issue by d4rkfella** [packruler/traefik-themepark#21]
After the more recent updates to bazarr there are some changes to the code of the web ui i think and the themes are no longer being applied correctly . Here is how it looks on my end . 
![1](https://github.com/user-attachments/assets/6380dd18-66d6-43cd-b878-6a557b688873)

**Comment by packruler** [comment]
I bet this issue is similar to other *arr apps. I'll try and get this fixed soon.

**Comment by d4rkfella** [comment]
Alright, thank you for the quick response :) Eagerly awaiting the update :P

**Comment by d4rkfella** [comment]
Hey, tried the new version but the issue still persist. Cleared cache and also tried a different theme but no luck .

**Comment by d4rkfella** [comment]
Maybe the issue is related to the theme itself and not actually how it is applied.

**Comment by packruler** [comment]
Interesting 🤔 I do not have Bazarr installed and did not test this fix. Looking at the docs for [theme-park](https://docs.theme-park.dev/themes/bazarr/) it appears Bazarr does not need the same override as [Radarr](https://docs.theme-park.dev/themes/radarr/#click-here-for-general-setup) and other *arr apps.
That said, you may want to post in theme-park's issues: https://github.com/themepark-dev/theme.park/issues

That said, I am going to roll back the update from yesterday as it is not warranted at this time, sorry for the false hope 😁
