### ISSUE TITLE
Feature: Support for Theme Addons

### ISSUE THREAD

**Issue by owine** [packruler/traefik-themepark#3]
**Is your feature request related to a problem? Please describe.**
Request to add support for the Theme Addons https://docs.theme-park.dev/themes/addons/

**Describe the solution you'd like**
Additional yaml entry for `addons:`

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by packruler** [comment]
I didn't realize these could be done outside of the Docker env... 😀 This should be possible and I will work to add support in the future 👍

**Comment by packruler** [comment]
Looking at how the addons work, I think it is only reasonable to add support for *arr addons. They are at least consistent and can be handled in a manner similar to how existing themes work.

That said, you or anyone, can setup a manual rewrite script using https://github.com/packruler/rewrite-body (this addon builds off of that one)

**Comment by saltydk** [comment]
Can you add documentation for how to specify addons using labels?
